project_id = "dcjizoulbggsavizbukq"

[functions.update-offers-daily]
verify_jwt = false

[functions.analyze-metrics]
verify_jwt = false

[functions.generate-whatsapp-funnel]
verify_jwt = false

[functions.webhook-new-sale]
verify_jwt = false

[functions.batch-create-users]
verify_jwt = false

[functions.generate-audio]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false
